sources:
- title: 'Accelerate: Building and Scaling High Performing Technology Organizations (Forsgren, Humble,
    Kim, 2018)'
  url: https://itrevolution.com/product/accelerate/
  publisher: IT Revolution
  accessed: '2026-08-30'
- title: 'Systems Performance: Enterprise and the Cloud (Gregg, 2020)'
  url: https://www.brendangregg.com/systems-performance-2nd-edition-book.html
  publisher: Addison-Wesley
  accessed: '2026-08-30'
- title: The Architecture of Open Source Applications (Brown & Wilson, 2012)
  url: https://aosabook.org/
  publisher: AOSA
  accessed: '2026-08-30'
