import pytest
import tempfile
from examples.ci_agent_runner import HeadlessCIAgentRunner

def test_execute_test_command_success():
    with tempfile.TemporaryDirectory() as tmpdir:
        runner = HeadlessCIAgentRunner(tmpdir)
        res = runner.execute_test_command("python3 -c 'print(\"CI OK\")'")
        assert res["exit_code"] == 0
        assert res["passed"] is True
        assert "CI OK" in res["stdout"]

def test_execute_test_command_failure():
    with tempfile.TemporaryDirectory() as tmpdir:
        runner = HeadlessCIAgentRunner(tmpdir)
        res = runner.execute_test_command("python3 -c 'exit(1)'")
        assert res["exit_code"] == 1
        assert res["passed"] is False

def test_generate_pr_summary_formatting():
    runner = HeadlessCIAgentRunner(".")
    summary = runner.generate_pr_summary(
        issue_id="88",
        title="Handle datetime timezone conversions",
        changes=["Added timezone parsing in serializer", "Added test_timezone_conversion unit test"]
    )
    assert "Resolves #88" in summary
    assert "Handle datetime timezone conversions" in summary
    assert "- Added timezone parsing in serializer" in summary
    assert "- Added test_timezone_conversion unit test" in summary
    assert "Automated test suite: `100% Passed`" in summary
    assert "Generated by Headless CI Coding Agent" in summary
