"""Marks the ten exercises in a starter file. Do not edit this file.

Usage (through the wrapper, which is what you should run):

    bash starter/02_check.sh
    bash starter/02_check.sh path/to/some/other/file.py

It loads the file by path, calls each exercise function with pinned inputs,
and compares against values that do not depend on when you run it. An
unfinished exercise raises NotImplementedError and is reported as not done,
not as a crash.
"""

from __future__ import annotations

import importlib.util
import os
import sys
from datetime import date, datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

UTC = timezone.utc
LONDON = "Europe/London"
HOUR = timedelta(hours=1)


def load(path: Path):
    spec = importlib.util.spec_from_file_location("starter_under_test", path)
    if spec is None or spec.loader is None:
        raise SystemExit(f"cannot load {path}")
    module = importlib.util.module_from_spec(spec)
    # Register it before executing: @dataclass looks the defining module up in
    # sys.modules, and a module loaded by path is not there unless we put it
    # there. Leaving this out fails with an AttributeError from dataclasses.
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class Marker:
    def __init__(self) -> None:
        self.done = 0
        self.total = 0
        self.notes: list[str] = []

    def exercise(self, number: int, title: str, body) -> None:
        self.total += 1
        try:
            body()
        except NotImplementedError:
            print(f"  {number:>2}. not started   {title}")
            return
        except AssertionError as exc:
            print(f"  {number:>2}. WRONG        {title}")
            print(f"      {exc}")
            return
        except Exception as exc:  # noqa: BLE001 - report anything, mark nothing
            print(f"  {number:>2}. ERROR        {title}")
            print(f"      {type(exc).__name__}: {exc}")
            return
        self.done += 1
        print(f"  {number:>2}. complete     {title}")


def equal(label: str, expected, actual) -> None:
    assert expected == actual, f"{label}: expected {expected!r}, got {actual!r}"


def main() -> int:
    target = Path(sys.argv[1] if len(sys.argv) > 1 else "starter/01_timezones.py")
    if not target.is_file():
        raise SystemExit(f"no such file: {target}")
    source = target.read_text(encoding="utf-8")
    module = load(target)
    marker = Marker()

    # Print a path relative to where the reader is standing, never an absolute
    # one: absolute paths leak somebody's home directory into captured output.
    relative = os.path.relpath(target, Path.cwd())
    print(f"Marking {relative if not relative.startswith('..') else target.name}\n")

    def ex1() -> None:
        count = module.zone_count()
        assert isinstance(count, int), f"expected an int, got {type(count).__name__}"
        assert count > 100, f"expected more than 100 zones, got {count}"
        import zoneinfo

        equal("zone count", len(zoneinfo.available_timezones()), count)

    def ex2() -> None:
        equal(
            "UTC instant",
            "2026-10-25T01:30:00Z",
            module.to_utc_text(datetime(2026, 10, 25, 1, 30, tzinfo=UTC)),
        )
        equal(
            "converted from London BST",
            "2026-08-16T11:00:00Z",
            module.to_utc_text(datetime(2026, 8, 16, 12, 0, tzinfo=ZoneInfo(LONDON))),
        )
        try:
            module.to_utc_text(datetime(2026, 8, 16, 12, 0))
        except ValueError:
            return
        raise AssertionError("a naive datetime should raise ValueError")

    def ex3() -> None:
        equal("2026-03-29 London", 23.0, module.day_length_hours(date(2026, 3, 29), LONDON))
        equal("2026-10-25 London", 25.0, module.day_length_hours(date(2026, 10, 25), LONDON))
        equal("2026-06-15 London", 24.0, module.day_length_hours(date(2026, 6, 15), LONDON))
        equal(
            "2026-03-08 New York",
            23.0,
            module.day_length_hours(date(2026, 3, 8), "America/New_York"),
        )

    def ex4() -> None:
        equal(
            "the repeated hour",
            (HOUR, timedelta(0)),
            tuple(module.ambiguous_offsets(datetime(2026, 10, 25, 1, 30), LONDON)),
        )
        equal(
            "an ordinary hour",
            (HOUR, HOUR),
            tuple(module.ambiguous_offsets(datetime(2026, 7, 1, 12, 0), LONDON)),
        )

    def ex5() -> None:
        equal("2026-03-29 01:30", True, module.is_nonexistent(datetime(2026, 3, 29, 1, 30), LONDON))
        equal("2026-03-29 02:30", False, module.is_nonexistent(datetime(2026, 3, 29, 2, 30), LONDON))
        equal("2026-10-25 01:30", False, module.is_nonexistent(datetime(2026, 10, 25, 1, 30), LONDON))
        equal("2026-06-15 01:30", False, module.is_nonexistent(datetime(2026, 6, 15, 1, 30), LONDON))

    def ex6() -> None:
        equal("2026-10-25 01:30", True, module.is_ambiguous(datetime(2026, 10, 25, 1, 30), LONDON))
        equal("2026-10-25 02:30", False, module.is_ambiguous(datetime(2026, 10, 25, 2, 30), LONDON))
        equal("2026-03-29 01:30", False, module.is_ambiguous(datetime(2026, 3, 29, 1, 30), LONDON))
        equal("2026-06-15 01:30", False, module.is_ambiguous(datetime(2026, 6, 15, 1, 30), LONDON))

    def ex7() -> None:
        instants = [
            datetime(2026, 8, 16, 18, 0, tzinfo=UTC),
            datetime(2026, 8, 16, 16, 0, tzinfo=UTC),
            datetime(2026, 8, 16, 15, 0, tzinfo=UTC),
            datetime(2026, 8, 16, 11, 30, tzinfo=UTC),
        ]
        expected = [
            "2026-08-16T11:30:00Z",
            "2026-08-16T15:00:00Z",
            "2026-08-16T16:00:00Z",
            "2026-08-16T18:00:00Z",
        ]
        equal("sorted text", expected, module.sorted_utc_texts(instants))

    def ex8() -> None:
        marks: list[int] = []
        elapsed = module.measure_elapsed(lambda: marks.append(1))
        assert marks == [1], "the callable was not called exactly once"
        assert isinstance(elapsed, float), f"expected a float, got {type(elapsed).__name__}"
        assert elapsed >= 0.0, f"a duration cannot be negative: {elapsed}"
        assert "time.monotonic" in source, "use time.monotonic(), not time.time()"

    def ex9() -> None:
        rules = module.LONDON_2026
        cases = [
            (datetime(2026, 1, 1, 12, 0, tzinfo=UTC), timedelta(0)),
            (datetime(2026, 3, 29, 0, 59, 59, tzinfo=UTC), timedelta(0)),
            (datetime(2026, 3, 29, 1, 0, 0, tzinfo=UTC), HOUR),
            (datetime(2026, 7, 1, 12, 0, tzinfo=UTC), HOUR),
            (datetime(2026, 10, 25, 0, 59, 59, tzinfo=UTC), HOUR),
            (datetime(2026, 10, 25, 1, 0, 0, tzinfo=UTC), timedelta(0)),
            (datetime(2026, 12, 25, 9, 0, tzinfo=UTC), timedelta(0)),
        ]
        london = ZoneInfo(LONDON)
        for instant, expected_offset in cases:
            got = module.offset_at_instant(instant, rules)
            equal(f"offset at {instant.isoformat()}", expected_offset, got)
            equal(
                f"zoneinfo agrees at {instant.isoformat()}",
                instant.astimezone(london).utcoffset(),
                got,
            )

    def ex10() -> None:
        rules = module.LONDON_2026
        london = ZoneInfo(LONDON)
        walls = [
            (datetime(2026, 1, 15, 12, 0), "normal"),
            (datetime(2026, 3, 29, 0, 59), "normal"),
            (datetime(2026, 3, 29, 1, 0), "nonexistent"),
            (datetime(2026, 3, 29, 1, 30), "nonexistent"),
            (datetime(2026, 3, 29, 1, 59), "nonexistent"),
            (datetime(2026, 3, 29, 2, 0), "normal"),
            (datetime(2026, 7, 1, 12, 0), "normal"),
            (datetime(2026, 10, 25, 0, 59), "normal"),
            (datetime(2026, 10, 25, 1, 0), "ambiguous"),
            (datetime(2026, 10, 25, 1, 30), "ambiguous"),
            (datetime(2026, 10, 25, 1, 59), "ambiguous"),
            (datetime(2026, 10, 25, 2, 0), "normal"),
            (datetime(2026, 12, 25, 9, 0), "normal"),
        ]
        for wall, expected_kind in walls:
            for fold in (0, 1):
                offset, kind = module.resolve_wall(wall, rules, fold)
                equal(f"kind of {wall.isoformat()}", expected_kind, kind)
                equal(
                    f"offset of {wall.isoformat()} fold={fold}",
                    wall.replace(tzinfo=london, fold=fold).utcoffset(),
                    offset,
                )

    marker.exercise(1, "zone_count", ex1)
    marker.exercise(2, "to_utc_text", ex2)
    marker.exercise(3, "day_length_hours", ex3)
    marker.exercise(4, "ambiguous_offsets", ex4)
    marker.exercise(5, "is_nonexistent", ex5)
    marker.exercise(6, "is_ambiguous", ex6)
    marker.exercise(7, "sorted_utc_texts", ex7)
    marker.exercise(8, "measure_elapsed", ex8)
    marker.exercise(9, "offset_at_instant", ex9)
    marker.exercise(10, "resolve_wall", ex10)

    print(f"\n{marker.done} of {marker.total} exercises complete.")
    return 0 if marker.done == marker.total else 1


if __name__ == "__main__":
    raise SystemExit(main())
