"""The dataset the Day 133 report is built from, and one perturbed copy.

Everything here is deterministic. `monthly_sales()` draws from a fixed
`numpy.random.default_rng(133)`, so two calls return identical frames and
two runs of the lab produce identical numbers. That determinism is not a
convenience -- exercise 6 asserts byte-identical output across two runs,
and a report generator that cannot be re-run to the same answer is not a
report generator, it is a one-off.

The frame deliberately contains four things a real exploratory analysis
would have to find:

1. **Missing revenue, not spread evenly.** About 4% of rows have no
   revenue, and every one of them is a `partner` row. Week 18's damage
   report exists to catch exactly this shape.
2. **Two populations in one column.** `partner` rows run at roughly 45%
   of the `direct` row for the same region and month, so the revenue
   column is a mixture, not a single distribution.
3. **A step change in one segment.** From month 13 the West is scaled by
   `WEST_PRICING_FACTOR`, standing in for a pricing change. The other
   three regions keep their steady monthly growth.
4. **One anomaly.** East, month 18, is scaled by `ANOMALY_FACTOR`. It is
   a single point, which is why the report that quotes it says plainly
   that no interval is available for it.

`perturbed()` returns a copy with one input changed. Exercises 3 and 6
use it to prove that the numbers printed in the report's prose come from
the data rather than from typed literals.
"""

from __future__ import annotations

import numpy as np
import pandas as pd

REGIONS: tuple[str, ...] = ("North", "South", "East", "West")
CHANNELS: tuple[str, ...] = ("direct", "partner")

N_MONTHS = 24
SEED = 133

#: From this month onward the West is scaled by WEST_PRICING_FACTOR.
PRICING_CHANGE_MONTH = 13
WEST_PRICING_FACTOR = 0.88

#: The single anomalous observation.
ANOMALY_REGION = "East"
ANOMALY_MONTH = 18
ANOMALY_FACTOR = 3.0

#: Share of rows whose revenue is missing. Every one is a partner row.
MISSING_RATE = 0.04

#: Partner rows run at this share of the same region-month direct row.
PARTNER_SHARE = 0.45

_BASE_LEVEL = {"North": 42000.0, "South": 31000.0, "East": 27000.0, "West": 36000.0}
_MONTHLY_GROWTH = {"North": 1.012, "South": 1.008, "East": 1.015, "West": 1.010}


def monthly_sales() -> pd.DataFrame:
    """Twenty-four months of revenue and orders for four regions and two
    channels: 192 rows, eight of them missing their revenue."""
    rng = np.random.default_rng(SEED)
    records: list[dict[str, object]] = []

    for month in range(1, N_MONTHS + 1):
        for region in REGIONS:
            for channel in CHANNELS:
                level = _BASE_LEVEL[region] * _MONTHLY_GROWTH[region] ** (month - 1)
                if channel == "partner":
                    level *= PARTNER_SHARE
                if region == "West" and month >= PRICING_CHANGE_MONTH:
                    level *= WEST_PRICING_FACTOR
                if region == ANOMALY_REGION and month == ANOMALY_MONTH:
                    level *= ANOMALY_FACTOR

                revenue = float(level * rng.normal(1.0, 0.05))
                order_value = float(rng.normal(180.0, 12.0))
                records.append(
                    {
                        "month": month,
                        "region": region,
                        "channel": channel,
                        "orders": int(round(revenue / order_value)),
                        "revenue": revenue,
                    }
                )

    frame = pd.DataFrame.from_records(records)

    partner_positions = np.asarray(frame.index[frame["channel"] == "partner"])
    n_missing = int(round(MISSING_RATE * len(frame)))
    blanked = rng.choice(partner_positions, size=n_missing, replace=False)
    frame.loc[blanked, "revenue"] = np.nan

    return frame


def perturbed() -> pd.DataFrame:
    """The same frame with exactly one input changed: the West's post-change
    scaling is halved again.

    Nothing else moves. If a number printed in the report's prose is the
    same for `monthly_sales()` and for this frame, that number was typed
    rather than computed -- which is the whole point of exercise 3.
    """
    frame = monthly_sales()
    hit = (frame["region"] == "West") & (frame["month"] >= PRICING_CHANGE_MONTH)
    frame.loc[hit, "revenue"] = frame.loc[hit, "revenue"] * 0.5
    return frame


def source_description() -> str:
    """One line of provenance, quoted verbatim in the rendered report."""
    return (
        "synthetic monthly sales, 4 regions x 2 channels x 24 months, "
        "generated by data.monthly_sales() with numpy default_rng(133)"
    )
