sources:
  - title: 'mixup: Beyond Empirical Risk Minimization'
    url: 'https://arxiv.org/abs/1710.09412'
    publisher: 'ICLR'
    accessed: '2026-08-29'
    year: 2018
    description: 'Hongyi Zhang, Moustapha Cisse, Yann Dauphin, and David Lopez-Paz introducing MixUp training.'
  - title: 'CutMix: Regularization Strategy to Train Strong Classifiers with Localizable Features'
    url: 'https://arxiv.org/abs/1905.04899'
    publisher: 'ICCV'
    accessed: '2026-08-29'
    year: 2019
    description: 'Sangdoo Yun et al. introducing CutMix patch replacement for visual regularization.'
  - title: 'RandAugment: Practical automated data augmentation with a reduced search space'
    url: 'https://arxiv.org/abs/1909.13719'
    publisher: 'NeurIPS'
    accessed: '2026-08-29'
    year: 2020
    description: 'Ekin D. Cubuk et al. establishing efficient automated augmentation policies.'
